# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
  task: "assemble",
  build_type: "release",
  properties: {
    "android.injected.signing.store.file" => "/Users/mohamedsalman/Documents/Canada Company/Projects/Continuous Integration/FastlaneJenkins/app/key0",
    "android.injected.signing.store.password" => "123456",
    "android.injected.signing.key.alias" => "key0",
    "android.injected.signing.key.password" => "123456",
  }
)
    upload_to_play_store(track: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
